apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql
    labels:
        app: mysql
spec:
    replicas: 1
    selector:
        matchLabels:
            app: my-mysql
    template:
        metadata:
            labels:
                app: my-mysql
        spec:
            containers:
            - name: mysql
              image: mysql
              ports:
              - containerPort: 3307
              volumeMounts:
              - name: mysql-storage
                mountPath: /var/lib/mysql
            volumes:
            - name: mysql-storage
              emptyDir: {}