version: '3.3'
services:
    db.data:
        image: mysql
        volumes:
            - ./mysql-init-files/:/docker-entrypoint-initdb.d/
        restart: always
        environment: 
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - "3306:3306"
    
    chat:
        image: chat:1.0.0
        ports:
            - "80:8080"
        depends_on:
            - db.data